window.voices = {
    monkDude: {
        name: "Apparition of Darkness",
        sfx: "drum",
        font: "marcellus",
        color: "crimson",
        speed: 0.85,
    },
    death: {
        name: "Death",
        sfx: "drum",
        font: "marcellus",
        color: "crimson",
        speed: 0.85,
    },
    deathEcho: {
        name: "Death",
        sfx: "drumEcho",
        font: "marcellus",
        color: "crimson",
        speed: 0.85,
    },
    deathEchoDelay: {
        name: "Apparition of Darkness",
        sfx: "drumEchoDelay",
        font: "marcellus",
        color: "crimson",
        speed: 0.85,
    },
    hero: {
        name: 'Me',
        sfx: 'regularVoice',
        font: 'exo',
        color: 'dodgerblue',
        speed: 1,
    },
    narrator: {
        name: null,
        sfx: 'godVoice',
        font: 'blackletter',
        color: 'var(--god-color)',
        speed: 1,
    },
    lostSoul: {
        name: 'Lost Soul',
        sfx: 'regularVoice',
        font: 'crimson',
        color: 'grey',
        speed: 1,
    },
    info: {
        name: null,
        sfx: null,
        font: 'kanit',
        color: 'tan',
        speed: 1,
    },
    vigilant: {
        name: 'A Vigilant',
        sfx: 'highVoice',
        font: 'medieval',
        color: 'gold',
        speed: 1,
    },
    devil: {
        name: 'The Devil',
        sfx: 'deepVoice',
        font: 'rocker',
        color: 'orangered',
        speed: 1,
    },
    king: {
        name: 'The King',
        sfx: 'deepVoice',
        font: 'pirata',
        color: 'rgb(0,255,50)',
        speed: 1,
    },
    demon: {
        name: 'Demon',
        sfx: 'deepVoice',
        font: 'salt',
        color: 'red',
        speed: 1,
    },
}